service: algo-rs

provider:
  name: aws
  region: us-west-1
  runtime: nodejs18.x

functions:
  cronFunction:
    handler: execute.main
    events:
       - schedule:
          rate: cron(0 21 ? * MON-FRI *)